name: Pulumi Deploy

on:
  push:
    paths:
      - 'pulumi/**'
  pull_request:
    paths:
      - 'pulumi/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: pulumi
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Pulumi dependencies
      run: |
        cd pulumi
        npm install

    - name: Set up Pulumi
      uses: pulumi/actions@v4
      with:
        command: up
        stack-name: PCritchfield/warmandcozy/dev
        work-dir: pulumi
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::123456789012:role/GithubActionsRole
        role-session-name: GitHubActions

    - name: Clean up pulumi
      uses: pulumi/actions@v4
      with:
        command: destroy
        stack-name: PCritchfield/warmandcozy/dev
        work-dir: pulumi
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
