name: Pulumi Deploy

on:
  push:
    paths:
      - 'pulumi/**'
  pull_request:
    paths:
      - 'pulumi/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Change to Pulumi directory
      run: cd pulumi

    - name: Set up Pulumi
      uses: pulumi/actions@3
      with:
        command: up
        stack-name: 
        work-dir: pulumi
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: your-aws-region
        role-to-assume: arn:aws:iam::123456789012:role/GithubActionsRole
        role-session-name: GitHubActions

    - name: Clean up pulumi
      uses: pulumi/actions@v2
      with:
        command: destroy
        stack-name: dev
        work-dir: pulumi
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
