name: Pulumi Deploy

on:
  push:
    paths:
      - 'pulumi/**'
  pull_request:
    paths:
      - 'pulumi/**'
      - '.github/workflows/deploy.yml'

jobs:
  preview:
    name: preview
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.5.0
      with:
        node-version: '21'
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::123456789012:role/GithubActionsRole
        role-session-name: GitHubActions

    - name: Install Pulumi dependencies
      run: |
        cd pulumi
        npm install

    - name: Set up Pulumi
      uses: pulumi/actions@v4
      with:
        command: preview
        stack-name: PCritchfield/warmandcozy/dev
        work-dir: pulumi
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    # - name: Clean up pulumi
    #   uses: pulumi/actions@v4
    #   with:
    #     command: destroy
    #     stack-name: PCritchfield/warmandcozy/dev
    #     work-dir: pulumi
    #   env:
    #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
